project-includes = ["tests/**/*.py"]
python-version = "3.11"
search-path = ["tests"]
check-unannotated-defs = true
infer-return-types = "never"
strict-callable-subtyping = true
strict-partial-subtyping = true
permissive-ignores = false

[errors]
unannotated-parameter = "error"
unannotated-return = "error"
unannotated-attribute = "error"
implicit-any = "error"
implicit-any-parameter = "error"
implicit-any-attribute = "error"
implicit-any-empty-container = "error"
implicit-any-lambda = "error"
implicit-any-type-argument = "error"
no-any-return = "error"
no-any-return-explicit = "error"
no-any-return-implicit = "error"
explicit-any = "error"
unknown-argument-type = "error"
unknown-attribute-type = "error"
unknown-variable-type = "error"
untyped-import = "error"
untyped-function-decorator = "error"
untyped-class-decorator = "error"
implicit-reexport = "error"
unused-ignore = "error"
unused-type-ignore = "error"
redundant-cast = "error"
redundant-condition = "error"
unnecessary-comparison = "error"
unnecessary-type-conversion = "error"
string-as-iterable = "error"
unreachable = "error"
